development: &default
  adapter: postgresql
  database: ads_development
  encoding: utf8
  host: 127.0.0.1
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  adapter:  postgresql
  database: ads_development

test:
  <<: *default
  database: ads_test

production:
  <<: *default
  database: ads_production

docker:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db
